hisi-drm-y := hisi_drm_drv.o \
	      hisi_ade.o \
	      hisi_drm_dsi.o \
	      hisi_drm_plane.o \
	      hisi_drm_crtc.o \
	      hisi_drm_encoder.o \
	      hisi_drm_connector.o \
	      hisi_drm_fb.o \

obj-$(CONFIG_DRM_HISI)	+= hisi-drm.o
obj-$(CONFIG_DRM_HISI_FBDEV) += hisi_drm_fbdev.o
